#!/bin/bash

# check for test mode
TEST=false
if [ "$1" == "-t" ]; then
    TEST=true
    shift
fi

if [ $# -ne 2 ]; then
    echo "Syntax: $0 <input.mp4> <output.mp4>"
    exit 1
fi

time2sec() {
    split=$(printf "$1" | tr ':' ' ')
    seconds=0
    for i in $split; do
        let seconds=$seconds*60+$i
    done

    printf "%d" $seconds
}

file=$1
cut_file=.cuts.cfg

> "$cut_file"

begin_clip=0
end_clip=
if $TEST; then
    echo "Clip begin:"
    read begin_clip
    echo "Clip end:"
    read end_clip
fi
printf "file '$file'\ninpoint $begin_clip\n" > $cut_file

while true; do
    echo "Cut start (blank to end):"
    read begin
    [ -z "$begin" ] && break
    echo "Cut end:"
    read finish

    start_s=$(time2sec "$begin")
    end_s=$(time2sec "$finish")
    
    printf "outpoint $start_s\nfile '$file'\ninpoint $end_s\n" >> $cut_file

done

if $TEST; then
    printf "outpoint $end_clip\n" >> $cut_file
fi

ffmpeg -f concat -i "$cut_file" -c copy "$2"

rm "$cut_file"
